// <auto-generated />
using DividendTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DividendTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240331200652_AddDividendTable")]
    partial class AddDividendTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DividendTracker.Models.Dividend", b =>
                {
                    b.Property<int>("DividendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DividendId"));

                    b.Property<decimal>("CurrentStockPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DividendAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayoutFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DividendId");

                    b.HasIndex("Ticker");

                    b.ToTable("Dividends");
                });

            modelBuilder.Entity("DividendTracker.Models.Stock", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ticker");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Ticker = "HEXA-B",
                            CompanyName = "Hexagon",
                            Sector = "Utilities"
                        },
                        new
                        {
                            Ticker = "NIBE-B",
                            CompanyName = "NIBE Industrier",
                            Sector = "Utilities"
                        },
                        new
                        {
                            Ticker = "NDA-SE",
                            CompanyName = "Nordea Bank",
                            Sector = "Finance"
                        },
                        new
                        {
                            Ticker = "ABB",
                            CompanyName = "ABB",
                            Sector = "Industrial"
                        },
                        new
                        {
                            Ticker = "SEB-A",
                            CompanyName = "SEB A",
                            Sector = "Finance"
                        },
                        new
                        {
                            Ticker = "SHB-A",
                            CompanyName = "Handelsbanken A",
                            Sector = "Finance"
                        },
                        new
                        {
                            Ticker = "SWED-A",
                            CompanyName = "Swedbank",
                            Sector = "Finance"
                        },
                        new
                        {
                            Ticker = "VOLV-B",
                            CompanyName = "Volvo B",
                            Sector = "Industrial"
                        },
                        new
                        {
                            Ticker = "TELIA",
                            CompanyName = "Telia Company",
                            Sector = "Communication"
                        },
                        new
                        {
                            Ticker = "EVO",
                            CompanyName = "Evolution",
                            Sector = "Consumer goods"
                        },
                        new
                        {
                            Ticker = "ALIV-SDB",
                            CompanyName = "Autoliv",
                            Sector = "Industrial"
                        },
                        new
                        {
                            Ticker = "ERIC-B",
                            CompanyName = "Ericsson B",
                            Sector = "Communication"
                        },
                        new
                        {
                            Ticker = "SCA-B",
                            CompanyName = "SCA B",
                            Sector = "Raw Material"
                        },
                        new
                        {
                            Ticker = "ATCO-A",
                            CompanyName = "Atlas Copco A",
                            Sector = "Industrial"
                        },
                        new
                        {
                            Ticker = "ATCO-B",
                            CompanyName = "Atlas Copco B",
                            Sector = "Industrial"
                        },
                        new
                        {
                            Ticker = "AZN",
                            CompanyName = "AstraZeneca",
                            Sector = "Pharma"
                        },
                        new
                        {
                            Ticker = "GETI-B",
                            CompanyName = "Getinge",
                            Sector = "Pharma"
                        },
                        new
                        {
                            Ticker = "INVE-B",
                            CompanyName = "Investor B",
                            Sector = "Investment company"
                        },
                        new
                        {
                            Ticker = "ASSA-B",
                            CompanyName = "Assa Abloy",
                            Sector = "Real Estate"
                        },
                        new
                        {
                            Ticker = "SAND",
                            CompanyName = "Sandvik",
                            Sector = "Industrial"
                        },
                        new
                        {
                            Ticker = "HM-B",
                            CompanyName = "Hennes & Mauritz",
                            Sector = "Consumer goods"
                        },
                        new
                        {
                            Ticker = "TEL2-B",
                            CompanyName = "Tele2 B",
                            Sector = "Communication"
                        },
                        new
                        {
                            Ticker = "ALFA",
                            CompanyName = "Alfa Laval",
                            Sector = "Industrial"
                        },
                        new
                        {
                            Ticker = "SKF-B",
                            CompanyName = "SKF B",
                            Sector = "Industrial"
                        },
                        new
                        {
                            Ticker = "BOL",
                            CompanyName = "Boliden",
                            Sector = "Raw Material"
                        },
                        new
                        {
                            Ticker = "ESSITY-B",
                            CompanyName = "Essity B",
                            Sector = "Consumer goods"
                        });
                });

            modelBuilder.Entity("DividendTracker.Models.Dividend", b =>
                {
                    b.HasOne("DividendTracker.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("Ticker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
